[project]
name = "pwnv"
version = "0.1.0"
description = "CLI tool for CTF management"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inquirerpy>=0.3.4",
    "pydantic>=2.10.3",
    "typer>=0.15.1",
]

[project.scripts]
pwnv = "pwnv:main"