#!/usr/bin/env python3
"""Generate the command reference from the Typer app.

The command tables in the docs used to be written by hand against ``--help``,
and they drifted: options were renamed, ``pwnv challenge env`` was documented as
``pwnv env``. Nothing catches that, because the docs and the CLI never meet.

This walks the real app and writes ``docs/reference/cli.md`` from it. CI runs
the same thing with ``--check``, so a command that changes without its
documentation fails the build instead of shipping.

Usage:
    python scripts/gen_cli_docs.py            # write the file
    python scripts/gen_cli_docs.py --check    # fail if it is out of date
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Iterator

import click
import typer.main

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "reference" / "cli.md"

HEADER = """<!--
Generated by scripts/gen_cli_docs.py - do not edit.
Change the Typer commands in pwnv/cli/ and run `python scripts/gen_cli_docs.py`.
-->

# Command Reference

Every command, generated from the CLI itself. `pwnv <command> --help` prints the
same thing in the terminal.

"""


def _escape(text: str) -> str:
    """Make help text safe for a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _default(param: click.Parameter) -> str:
    """Render a default the way someone reading it would type it."""
    value = param.default
    if value is None or value is False:
        return ""
    if value is True:
        return "`true`"
    if isinstance(value, (list, tuple)):
        return " ".join(f"`{item}`" for item in value) if value else ""
    text = str(value)
    # A default built from `Path.cwd()` is whoever ran the generator's directory,
    # and would differ between a laptop and CI. Say where it is relative to.
    for base, prefix in ((Path.cwd(), "./"), (Path.home(), "~/")):
        if text.startswith(f"{base}/"):
            return f"`{prefix}{text[len(str(base)) + 1 :]}`"
    return f"`{text}`"


def _type_name(param: click.Parameter) -> str:
    if isinstance(param.type, click.Choice):
        return " \\| ".join(f"`{choice}`" for choice in param.type.choices)
    name = param.type.name
    return "" if name == "boolean" else f"`{name.upper()}`"


def _options(command: click.Command) -> list[click.Option]:
    return [
        param
        for param in command.params
        if isinstance(param, click.Option) and not param.hidden
    ]


def _arguments(command: click.Command) -> list[click.Argument]:
    return [param for param in command.params if isinstance(param, click.Argument)]


def _walk(
    command: click.Command, path: list[str]
) -> Iterator[tuple[list[str], click.Command]]:
    """Yield every leaf command, breadth first, in the order Typer declares it."""
    if isinstance(command, click.Group):
        for name, child in command.commands.items():
            yield from _walk(child, [*path, name])
        return
    yield path, command


def _usage(path: list[str], command: click.Command) -> str:
    ctx = click.Context(command, info_name=" ".join(path))
    return " ".join([*path, *command.collect_usage_pieces(ctx)])


def _describe(command: click.Command) -> str:
    text = (command.help or command.short_help or "").strip()
    # Typer keeps the docstring verbatim; the first paragraph is the summary.
    paragraphs = [
        " ".join(line.strip() for line in block.splitlines() if line.strip())
        for block in text.split("\n\n")
    ]
    return "\n\n".join(block for block in paragraphs if block)


def _render(path: list[str], command: click.Command) -> str:
    lines = [f"### `{' '.join(path)}`", ""]
    description = _describe(command)
    if description:
        lines += [description, ""]
    lines += ["```", _usage(path, command), "```", ""]

    arguments = _arguments(command)
    if arguments:
        lines += ["| Argument | Type | Required |", "| :--- | :--- | :--- |"]
        for argument in arguments:
            required = "yes" if argument.required else "no"
            name = (argument.metavar or argument.name or "").upper()
            lines.append(f"| `{name}` | {_type_name(argument)} | {required} |")
        lines.append("")

    options = [option for option in _options(command) if option.name != "help"]
    if options:
        lines += [
            "| Option | Type | Default | Description |",
            "| :--- | :--- | :--- | :--- |",
        ]
        for option in options:
            names = option.opts + option.secondary_opts
            flags = ", ".join(f"`{flag}`" for flag in names)
            help_text = _escape(option.help or "")
            if option.envvar:
                envvars = (
                    option.envvar
                    if isinstance(option.envvar, str)
                    else ", ".join(option.envvar)
                )
                help_text = f"{help_text} (env: `{envvars}`)".strip()
            lines.append(
                f"| {flags} | {_type_name(option)} | {_default(option)} | {help_text} |"
            )
        lines.append("")
    return "\n".join(lines)


def build() -> str:
    from pwnv import app as typer_app

    root: Any = typer.main.get_command(typer_app)
    sections: dict[str, list[str]] = {}
    for path, command in _walk(root, ["pwnv"]):
        group = path[1] if len(path) > 2 else "pwnv"
        sections.setdefault(group, []).append(_render(path, command))

    parts = [HEADER]
    # Top-level commands first: `pwnv init` is what a reader is looking for.
    ordered = sorted(sections.items(), key=lambda item: item[0] != "pwnv")
    for group, rendered in ordered:
        title = "Top level" if group == "pwnv" else f"`pwnv {group}`"
        parts.append(f"## {title}\n")
        parts.extend(rendered)
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    generated = build()
    if "--check" in sys.argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current == generated:
            return 0
        print(
            f"{OUTPUT.relative_to(ROOT)} is out of date.\n"
            "Run `python scripts/gen_cli_docs.py` and commit the result.",
            file=sys.stderr,
        )
        import difflib

        sys.stderr.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile="committed",
                tofile="generated",
            )
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
